### PR TITLE
Add product vision feedback

### PR DESCRIPTION
**Pull request by aaronang**

### CODE REVIEW

**Comment by mdingjan** [comment]
I've read the feedback and understand it. ;)

Ready for merging.

**Comment by mpsijm** [comment]
The capitalization link is way too buggy to be used XD But the feedback is clear, for the parts that are filled in. Is there a reason why the last three parts have no feedback?

**Comment by aaronang** [comment]
@mpsijm In what sense is capitalization app buggy? I never had problems with it before.
No feedback means that I found it good :wink:

**Comment by mpsijm** [comment]
@aaronang Thanks in that case :D 
And it's buggy in the sense that editing the title in the input box sometimes makes the cursor jump to the end. But when copy-pasting titles in there it works :P

**Comment by MathiasMeuleman** [comment]
About time this gets merged! Thanks @aaronang

**Pull request merged**
