### PR TITLE
102 set error status

### LINKED ISSUE #102: Set error status on the right moments
- [x] When the Tab should be refreshed, this should be reflected in the status. (fixed because tab now automatically refreshes)
- [ ] When the Tab errors, this should be reflected in the status.

### PR DESCRIPTION
**Pull request by mpsijm**
Will close #102 
~~Please merge #188 and #189 first, as this PR depends on those PRs.~~

I made sure the `ERROR` status is set on two occasions:

- The DatabaseAdapter calls the failure callback
- The ContentController errors while hooking to DOM

If there are other occasions that should have an `ERROR` status, please tell me :)

Have fun breaking our extension :D

### CODE REVIEW

**Comment by mdingjan** [comment]
Running on reload popped up again.. :o

**Comment by mpsijm** [comment]
I have confirmed and identified the bug indeed :open_mouth: Will fix now :)

**Comment by mpsijm** [comment]
I fixed it :) A fun way to test this is to `throw "duck";` on line 88 of the `ContentController` (inside the `try` block) :smile:

**Comment by mdingjan** [comment]
The bug has indeed been fixed. Thanks! :)

**Comment by thervh70** [comment]
Looks good. The error status pops up nicely.

Will merge!

**Pull request merged**
