### PR TITLE
CEQ 1 Feedback

### PR DESCRIPTION
**Pull request by breijm**
Questions, Comments, Feedback - all are welcome

### CODE REVIEW

**Comment by mpsijm** [comment]
The documents are peer-reviewed on Google Docs, this is a lot easier to do with Docs' comment system. Once we're done peer reviewing, the binary pdfs have to be pushed only once.

**Comment by mdingjan** [comment]
I've read the feedback; we'll take the notes into account. Please have a look at Maarten's comment on one of the notes, the rest is clear.
I also understand the grades; we will especially work on Tooling and Testing :)

**Comment by breijm** [comment]
@mpsijm Makes sense but because I don't have access to Google Drive, a quick review in the pull-request shows me that you've done this and I can justify your grade better. It's a matter of documenting proof that you've actually done what we require. Hope that makes sense

**Comment by mpsijm** [comment]
@breijm Would a complete copy of the comment history per document be sufficient? Or do you want access to our Drive folders so you can see the comments there? We dislike having a Pull Request + review for the documents just for the sake of it, even as a sanity check, as it is much easier to do this sanity check on Drive where we can all concurrently write text and add comments.

**Comment by mpsijm** [comment]
I think we can merge this PR for now, we will improve this point in our next sprints. You guys agree?

**Pull request merged**
