### PR TITLE
Feedback Code Evolution Quality 2

### PR DESCRIPTION
**Pull request by breijm**
Questions, Comments, Feedback - Let me know

### CODE REVIEW

**Comment by mpsijm** [comment]
Feedback processed in #26, as I was working on the Database there anyway :)

**Comment by mdingjan** [comment]
About one of your notes with relation to outputting Travis' build results.
We already do this via a private channel (for our group) in Slack. 

We can add the results of Travis to GitHub, but maybe you can (also) join us in that channel, if you want to, so that you can have a look at the builds. :)

Maybe something for the meeting tomorrow. :)

**Comment by mdingjan** [comment]
I agree with the feedback. Last sprint we forgot to add the updated ADD, as we thought we wouldn't get another grade for it after the draft and before the final version, so we'll update it this time. ;)

Ready for merging, in my opinion.

**Comment by thervh70** [comment]
Feedback is proccessed and discussed in the meeting.

Will merge.

**Pull request merged**
