### PR TITLE
15 typedef manager

### LINKED ISSUE #15: Improve management of type definitions
Currently, we import the entire submodule of DefinitelyTyped. We need a type definition manager in which we can select which type definitions​ we need.

### PR DESCRIPTION
**Pull request by mpsijm**
I added the new package "Typings" to get rid of the enormous submodule "DefinitelyTyped".
Will close #15.
Please review and merge :)

### CODE REVIEW

**Comment by Exclaminator** [comment]
Please fix the Continious integration first.

**Comment by mpsijm** [comment]
Fixed it, re-opened for review again :)

**Comment by mdingjan** [comment]
I've worked myself a way through the changes and agree with them. ;)
It's a nice enhancement!

Ready for merging in my opinion.

**Comment by thervh70** [comment]
The diff is huge as well as the improvement boost when it comes to autocompletion.
This is a nice enhancement indeed!

I will merge this.

**Pull request merged**
