### PR TITLE
Added removeobserver

### PR DESCRIPTION
**Pull request by thervh70**
Small code change based on SE-TA feedback.

### CODE REVIEW

**Comment by mpsijm** [comment]
Thanks for the addition, but I think this should be tested.

**Comment by thervh70** [comment]
@mpsijm fair point, but i think I will do this as a commit in #67. Just to prevent merge conflicts when that branch gets pushed to dev.

In order for that to happen this branch must be merged to dev, so please continue the review!

**Comment by thervh70** [comment]
Basic testing will fail due to the lack of a proper `chrome.storage.sync` mocking object. This object is needed to call the `Options.init()` method. Changing the code based on this is not the way to go, i guess. Any advice?

**Comment by MathiasMeuleman** [comment]
The code looks fine! If the chrome.storage mock is needed for testing, this should be able to be tested in the near future. Because this piece of code is not providing functionality for the extension (yet), it shouldn't be a problem to wait.

**Comment by Exclaminator** [comment]
Looks good, should be tested tho., maybe we should restructure the Options class to be instantiated to refer to either the chrome storage or a mocked object.

**Comment by mpsijm** [comment]
I think that's not something we want. Besides, this issue was about adding a `removeObserver` method, which indeed can not easily be tested because of the chrome storage issue.

@mdingjan is at the moment looking into mocking Chrome storage in #67. This PR can be merged for now in that case, and once we have the power to mock chrome storage, we'll test this method as well :) 

You guys agree?

**Comment by mdingjan** [comment]
I agree with @mpsijm. I'm researching it and processing tests for chrome related functions and properties.
Ready for merging for the moment.

**Comment by mdingjan** [comment]
Will merge!

**Comment by mdingjan** [comment]
Can't merge from my phone.. :P GitHub doesn't allowe to :P

**Pull request merged**
