### PR TITLE
SE feedback product planning draft

### PR DESCRIPTION
**Pull request by breijm**
Questions, comments, feedback all is welcome.

### CODE REVIEW

**Comment by Exclaminator** [comment]
Reviewed the feedback, ok for merge.

**Comment by mpsijm** [comment]
I agree with the feedback, this can be merged.

**Comment by mdingjan** [comment]
I've read the feedback and I agree with it. Ready for merging.

**Comment by MathiasMeuleman** [comment]
@breijm The guidelines specifically asked us for a high-level backlog. Do you still want us to give the details you asked for in section ##Product?

**Comment by breijm** [comment]
High-level refers to the requirements being about the entire product (as opposed to specific features); the requirements can (and must) be concrete, otherwise you won't know if the requirement has been met. No need to add new requirements or much more text, just make sure the current requirements are as concrete as possible.

**Comment by breijm** [comment]
Ex: the extension will log the mouse and click actions of the user

This is already more concrete than simply actions

**Pull request merged**
