### PR TITLE
Change settup variables

### PR DESCRIPTION
**Pull request by Exclaminator**
I have changed some env variables, could you (my peers) please check if this makes webstorm work properly. So that the files are shown in the IDE, with folders, that you're able to create files and that they transpile to javascript.

Thanks in advance.

### CODE REVIEW

**Comment by mpsijm** [comment]
It works for me, ready to be merged :)

**Comment by mdingjan** [comment]
It works for me as well :)
Ready for merging in my opinion ;)

**Comment by thervh70** [comment]
It works great on my machine. Please merge this.

**Comment by mpsijm** [comment]
I have seen it work at Mathias' PC as well, so I'll merge now :)

**Pull request merged**
