### PR TITLE
Update URL to new Octopeer server url

### PR DESCRIPTION
**Pull request by mpsijm**
Since @aaronang has the new Octopeer server running,
we can change the URL in our system as well :)

### CODE REVIEW

**Comment by thervh70** [comment]
500 errors experience by @mpsijm ...

**Comment by mdingjan** [comment]
Works for me.
Ready for merging!

**Comment by mpsijm** [comment]
The 500s were caused by a duplicate user on the server (for which Mitchell didn't have a problem luckily). Robin and I both had our username duplicate in the database. This is probably due to concurrency issues on the server side.

**Comment by thervh70** [comment]
So how will we prevent this from happening in the future? Also: how will we (@mpsijm and I) get a working version of the extension when our names are dulpicated..

**Comment by mpsijm** [comment]
Unfortunately, we can't do anything with the database without @aaronang. He can either flush the database (this doesn't prevent from duplicates happening in the future) or try to fix it (which takes more time).

**Comment by mpsijm** [comment]
Okay, @aaronang flushed the database and it works for me now :) Can you guys please also take another look? :)

**Comment by mdingjan** [comment]
I've had another look; it still works nicely for me. :)

**Comment by thervh70** [comment]
Nope
Nope.

**Comment by thervh70** [comment]
Aaron made the username unique. Therefore I would like @mpsijm and @mdingjan to test this one last time. Then one of you can merge this!

**Comment by mpsijm** [comment]
I'm lonely again, in the database that is :P Works for me, so if anybody else can confirm it works, it can be merged :)

**Comment by mdingjan** [comment]
Still works for me! Will merge!

**Pull request merged**
