### PR TITLE
Added a SonarQuack section to the readme

### PR DESCRIPTION
**Pull request by mdingjan**
Will close nothing.

Added a SonarQuack section to the readme.

Please review! :)
Quack.

### CODE REVIEW

**Comment by mpsijm** [comment]
I think this part belongs below the "Adding new dependencies" part, since that belongs also to the setting up and installing of our extension. The Visualisation is just extra :)
Content is looking good though :)

**Comment by mdingjan** [comment]
@mpsijm I agree, will do! :)

**Comment by mdingjan** [comment]
@mpsijm There we go :)

**Comment by mpsijm** [comment]
Yes, thanks for your change :D Can be merged :)

**Comment by thervh70** [comment]
Yay SonarQuack!! I want this to be merged. So I'll merge!

**Pull request merged**
