### PR TITLE
71 toggle button

### LINKED ISSUE #71: Implement toggle button
Implement the toggle button in the Octopeer menu

- [x] Make the toggle button function
- [x] Change the text of the Options button to a gear wheel image

### PR DESCRIPTION
**Pull request by thervh70**
Will close #71 

Added functionality to toggle button.
Changed looks (yay for materialize)

### CODE REVIEW

**Comment by mpsijm** [comment]
I like the addition, but now there are multiple places that the extension can be turned off, I think the options page should listen to the storage and show/hide the sub-options from there (and also change the global switch option accordingly)

**Comment by mpsijm** [comment]
Either that, or disable the browserAction popup while in the Options page (that's a lot easier XD)

**Comment by thervh70** [comment]
@mpsijm fixed the problem you stated.

Yet found a different problem: toggling in a PR gives a faulty status (standby instead of running)
This can be fixed as soon as a separate URL parser class is fixed (Action point for @mpsijm discussed in the "headstogether" meeting)

**Comment by thervh70** [comment]
Fixed the bug stated above. Branch is open for review again!

**Comment by mpsijm** [comment]
Can you add a ticket for the new bug, with a clear description of what is wrong?

**Comment by thervh70** [comment]
@mpsijm the bug was fixed! See the latest commit.

**Comment by mpsijm** [comment]
Okay, the toggle button seems broken right now...?

**Comment by thervh70** [comment]
You are right @mpsijm. Right now that option is not linked to the backend. I've added a new ticket for that issue ( #80 )

**Comment by mpsijm** [comment]
You're right, it's better to split that issue, else this becomes too large. Approve for merge granted! :)

**Comment by mdingjan** [comment]
Too large? Will you fix this new issue within this sprint, Robin?
Else we've got a broken toggle button during the demo..

**Comment by thervh70** [comment]
@mdingjan It's not really broken. It just has no functionality besides visuals and the chrome storage. The backend does not respond to any of the options right now.

**Comment by MathiasMeuleman** [comment]
I agree that the back-end connection should be fixed in a new issue. There is however a front-end request from my part. I would really like to see the Submit button gone on the Options page. Right now, Materialize.toast is called on every click, giving a false sense of data storage (like when you click the tick in the General tab, a toast appears saying 'Logging disabled'). It would make sense the option is then saved, but instead you also have to click Submit. Not very clean, needs additional user input. Maybe this is something to test during the Usability Test? I however am convinced it should go

**Comment by MathiasMeuleman** [comment]
Rest of the PR is fine btw :)

**Comment by mpsijm** [comment]
This feature request is too large and does not belong to this PR. I want this feature too though, so I made a ticket for it ( #89 ). However, currently something seems broken: whenever the extension is "on" its status is always "running" while it should be "standby" on the correct pages. Can you still fix this @thervh70?

**Comment by thervh70** [comment]
Fixed the bug using some code from @mpsijm 's branch. Looks like this feature is done now (finally)!

**Comment by mpsijm** [comment]
Yess it works, ready for merging once Travis is happy :)

**Comment by mdingjan** [comment]
I've reviewed your changes and made some (small) minor changes.
Your cherry picked equals function for arrays actually needs a test.. I'll just do this in #67 or @mpsijm can do that in #50, if not already done.

**Comment by mpsijm** [comment]
@mdingjan I will do this quickly in #88 #50 then. Thanks for noticing :)

**Comment by mdingjan** [comment]
@mpsijm Thanks :)
Then this PR is ready for merging.
Will merge!

**Pull request merged**
